"""Domain data models for document ingestion and structure-aware chunking."""

from datetime import datetime, timezone
from typing import Optional
from pydantic import BaseModel, Field


class DocumentPage(BaseModel):
    """Raw parsed text corresponding to a single document page or section segment."""

    page_number: Optional[int] = Field(default=None, description="1-indexed physical page number.")
    text: str = Field(..., description="Raw text extracted from this page or segment.")


class ParsedDocument(BaseModel):
    """Normalized document representation generated by file parsers."""

    document_id: str = Field(..., description="Canonical SHA-256 hash of original file content.")
    filename: str = Field(..., description="Original filename uploaded by client.")
    file_type: str = Field(..., description="Normalized document type: 'pdf', 'docx', or 'txt'.")
    file_size_bytes: int = Field(..., ge=0, description="Raw file size in bytes.")
    pages: list[DocumentPage] = Field(default_factory=list, description="Extracted pages or segments.")
    domain: Optional[str] = Field(default=None, description="Legal domain classification if provided.")
    raw_text: str = Field(..., description="Full concatenated text across all document pages.")


class DocumentChunk(BaseModel):
    """
    Evidence-First chunk ready for vectorization and indexing in Qdrant.
    
    Includes structural anchors (Section, Heading, Page) and graph adjacency pointers.
    """

    chunk_id: str = Field(..., description="Deterministic UUIDv5 derived from document_id and chunk_index.")
    document_id: str = Field(..., description="SHA-256 hash of the parent document.")
    document_name: str = Field(..., description="Sanitized original document filename.")
    source: str = Field(..., description="Canonical document reference or filename.")
    file_type: str = Field(..., description="Document extension / type.")
    page_number: Optional[int] = Field(default=None, description="Source page number where chunk originated.")
    chunk_index: int = Field(..., ge=0, description="0-indexed position within the document's sequence.")
    section: str = Field(..., description="Detected statutory section or contract clause (e.g. 'Section 185').")
    sub_section: Optional[str] = Field(default=None, description="Detected sub-section or sub-clause.")
    heading: Optional[str] = Field(default=None, description="Heading or title preceding the chunk text.")
    domain: Optional[str] = Field(default=None, description="Legal domain tag.")
    text: str = Field(..., description="Verbatim textual body of the chunk.")
    act_name: str = Field(..., description="Act or primary statute name (defaults to document_name).")
    prev_chunk_id: Optional[str] = Field(default=None, description="UUIDv5 of the immediately preceding chunk.")
    next_chunk_id: Optional[str] = Field(default=None, description="UUIDv5 of the immediately following chunk.")
    token_count: int = Field(..., ge=1, description="Estimated token length of the chunk body.")
    created_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="UTC creation timestamp.",
    )

    def to_qdrant_payload(self) -> dict:
        """Converts chunk model into Qdrant-compatible point payload."""
        payload = self.model_dump()
        # Dual-key mapping for backward compatibility with existing retrieval nodes
        payload["content"] = self.text
        return payload
